### ISSUE TITLE
Issue when loading the PivotGridSelector, error: Cannot read property 'top' of undefined

### ISSUE THREAD

**Issue by snkrishnan1** [IgniteUI/igniteui-angular2#140]
I am facing some issues when I load the PivotGrid along with the PivotGridSelector. When I try to load along with Selector, then the PivotGrid is not getting loaded properly i.e. only partialy it is getting loaded and the timer is dispayed for infinite time. 
I am getting the error in the browser console: "

> Error occurred. Error: Error in HTML/Reports/PivotGrid.html:11:35 caused by: Cannot read property 'top' of undefined

".
but when I comment the below code which is used to load the selector, then pivotgrid alone loads fine and no issues in it.
I want to have both the pivotgrid and the selector loaded so that dynamically the user can configure the pivot grid by changing the measures etc.

Please find the html code
```
<ig-pivot-data-selector [widgetId]="selectorId" id="dataSelector" [options]="optsSelector">
</ig-pivot-data-selector>
<ig-pivot-grid [widgetId]="gridId" [options]="optsGrid">
</ig-pivot-grid>
```

The angular2 component is attached
Also I am attaching the json contents returned by webapi which is retrieved dynamically by this pivotgrid component.
**this.cacheDataService.GetData.txt**   - this.cacheDataService.GetData(this.cacheurl).subscribe(reslt => {..}
**this.configService.GetWidgetConfig**  - this.configService.GetWidgetConfig(_reportID).subscribe(res => {..}

Note: about the version of controls being used, I have downloaded the latest "Full Product - version 16.2" and installed locally, I am referencing the .js and .css libraries locally.
[SelectorIssue.zip](https://github.com/IgniteUI/igniteui-angular2/files/845671/SelectorIssue.zip)

**Comment by snkrishnan1** [comment]
Stack Trace of the 'top' undefined issue
Uncaught TypeError: Cannot read property 'top' of undefined																									infragistics.lob.js:662
    at e.(anonymous function).(anonymous function)._positionOverlayDropAreas (http://localhost:49928/js/IgniteUI/infragistics.lob.js:662:19495)
    at e.(anonymous function).(anonymous function)._positionOverlayDropAreas (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at e.(anonymous function).(anonymous function)._onDataRendered (http://localhost:49928/js/IgniteUI/infragistics.lob.js:662:18161)
    at e.(anonymous function).(anonymous function)._onDataRendered (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at HTMLTableElement.dataRendered (http://localhost:49928/js/IgniteUI/infragistics.lob.js:661:12953)
    at e.(anonymous function).(anonymous function)._trigger (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:13009)
    at e.(anonymous function).(anonymous function)._renderData (http://localhost:49928/js/IgniteUI/infragistics.lob.js:138:17643)
    at e.(anonymous function).(anonymous function)._renderData (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at e.(anonymous function).(anonymous function).e (http://code.jquery.com/jquery-1.11.3.min.js:2:3959)
    at Class._invokeCallback (http://localhost:49928/js/IgniteUI/infragistics.core.js:270:30197)

**Comment by dkamburov** [comment]
You are not setting the widgetId property correctly. 

```
<ig-pivot-grid [widgetId]="gridId" [options]="optsGrid">
</ig-pivot-grid>
```
`gridId` should be defined into the constructor of your `PivotGrid` class. So that the pivot grid can be created with the appropriate id.

**Comment by snkrishnan1** [comment]
It works fine with this fix, thanks
