### ISSUE TITLE
Not able to load the PivotGridSelector component in the child component

### ISSUE THREAD

**Issue by snkrishnan1** [IgniteUI/igniteui-angular2#141]
I wanted to load the PivotGrid and the PivotGridSelector in 2 separate component i.e. in 2 different angular2 and its HTML layout respectively. The PivotGrid should be loaded in the main window/parent component and the PivotGridSelector should be loaded in a separate html i.e. child component which I am referring as slideout component. Please refer the snapshot for more information.
The Problem I am facing is when I have both the selectors and PivotGrid in the same component, it works fine i.e. loads both the PivotGrid and PivotGridSelector. But When I move the PivotGridSelector selector to other component/html which is sub-component to parent PivotGrid it doesn't load the PivotGridSelector. Only the PivotGrid is loaded but not the PivotGridSelector

How to load the PivotGridSelector in a different component? Any ideas why I am not able to load it in different component/html layout?

[SelectorChildComponentIssue.zip](https://github.com/IgniteUI/igniteui-angular2/files/846491/SelectorChildComponentIssue.zip)

Note: Please find the expected behavior in the attached snapshot. This functionality we're able to do in some other 3rd part component. But we are facing issues in implementing it in IgniteUI

**Comment by snkrishnan1** [comment]
Now I am able to load the Selector on the child component, I am attaching the code changes which I did to make it work. But still I am facing some other issues as mentioned below
1. When I do the Drag-drop in the selector to Edit the measures/rows/Columns, after closing the slideout/Selector still I see the stains of the items which I selected for Darg-Drop - Please refer the snapshot for more info. How do i remove those? What are the CSS changes to be done?
2. When I try to expand on the Row-wise, it gets to infinite timer dispay and the grid hangs-out. I get the error message as "TypeError: Cannot read property 'top' of undefined"
3. Not able to view the Filter options on the Rows in the selector window. I tried changing the Z-index but still the Filter is not coming on top. any ideas how to bring it on top i.e. above any html contents (selector window). Please refer snapshot
[Selector Stains Issue.zip](https://github.com/IgniteUI/igniteui-angular2/files/848725/Selector.Stains.Issue.zip)

Stack Trace of the top undefined issue
Uncaught TypeError: Cannot read property 'top' of undefined																									infragistics.lob.js:662
    at e.(anonymous function).(anonymous function)._positionOverlayDropAreas (http://localhost:49928/js/IgniteUI/infragistics.lob.js:662:19495)
    at e.(anonymous function).(anonymous function)._positionOverlayDropAreas (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at e.(anonymous function).(anonymous function)._onDataRendered (http://localhost:49928/js/IgniteUI/infragistics.lob.js:662:18161)
    at e.(anonymous function).(anonymous function)._onDataRendered (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at HTMLTableElement.dataRendered (http://localhost:49928/js/IgniteUI/infragistics.lob.js:661:12953)
    at e.(anonymous function).(anonymous function)._trigger (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:13009)
    at e.(anonymous function).(anonymous function)._renderData (http://localhost:49928/js/IgniteUI/infragistics.lob.js:138:17643)
    at e.(anonymous function).(anonymous function)._renderData (http://code.jquery.com/ui/1.11.1/jquery-ui.min.js:6:7983)
    at e.(anonymous function).(anonymous function).e (http://code.jquery.com/jquery-1.11.3.min.js:2:3959)
    at Class._invokeCallback (http://localhost:49928/js/IgniteUI/infragistics.core.js:270:30197)

**Comment by dkamburov** [comment]
This is the same error as issue #140. Please make sure you're setting the property of `widgetId `initially or into the constructor. From this depends the correct initialization of the widget and setting another options to it.

**Comment by snkrishnan1** [comment]
It works with that fix, thanks
