### ISSUE TITLE
Error: Can't resolve all parameters for IgDataChartComponent: (?, ?, ?).

### ISSUE THREAD

**Issue by sherry9872** [IgniteUI/igniteui-angular2#81]
Error: Can't resolve all parameters for IgTextEditorComponent: (?, ?, ?, ?).

Getting the above errors when using with angular2 RC5 routing and ngmodule

**Comment by dkamburov** [comment]
I've prepared a sample with ngModule and routing with the IgTextEditorComponent and IgGridComponent. 

Please review it and let me know if you can modify it to demonstrate the behavior you are observing.
[ngModule_routing.zip](https://github.com/IgniteUI/igniteui-angular2/files/459254/ngModule_routing.zip)

**Comment by sherry9872** [comment]
Still getting the below error. What am i missing?
Error: Error: Can't resolve all parameters for IgGridComponent: (?, ?, ?).
	    at new BaseException (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:5116:27)
	    at CompileMetadataResolver.getDependenciesMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13527:23)
	    at CompileMetadataResolver.getTypeMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13424:30)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13142:42)
	    at Array.map (native)
	    at CompileMetadataResolver.getDirectiveMetadata (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13138:79)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13593:37)
	    at Array.forEach (native)
	    at CompileMetadataResolver._getEntryComponentsFromProvider (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13592:34)
	    at eval (https://npmcdn.com/@angular/compiler@2.0.0-rc.5//bundles/compiler.umd.js:13563:87)
	Error loading http://localhost:5000/app/bootstrap.ts

**Comment by dkamburov** [comment]
Have you tried this one with 2.0.0 ?

**Comment by kdinev** [comment]
Closing this one as inactive.
